// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: proto/bank/type/account.proto

package bank

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurrentBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentBalanceReq) Reset() {
	*x = CurrentBalanceReq{}
	mi := &file_proto_bank_type_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentBalanceReq) ProtoMessage() {}

func (x *CurrentBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentBalanceReq.ProtoReflect.Descriptor instead.
func (*CurrentBalanceReq) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_account_proto_rawDescGZIP(), []int{0}
}

func (x *CurrentBalanceReq) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type CurrentBalanceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	CurrentDate   *date.Date             `protobuf:"bytes,2,opt,name=current_date,proto3" json:"current_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentBalanceRes) Reset() {
	*x = CurrentBalanceRes{}
	mi := &file_proto_bank_type_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentBalanceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentBalanceRes) ProtoMessage() {}

func (x *CurrentBalanceRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentBalanceRes.ProtoReflect.Descriptor instead.
func (*CurrentBalanceRes) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_account_proto_rawDescGZIP(), []int{1}
}

func (x *CurrentBalanceRes) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CurrentBalanceRes) GetCurrentDate() *date.Date {
	if x != nil {
		return x.CurrentDate
	}
	return nil
}

type CreateAccountReq struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	AccountName          string                 `protobuf:"bytes,1,opt,name=account_name,proto3" json:"account_name,omitempty"`
	Currency             string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	InitialDepositAmount float64                `protobuf:"fixed64,3,opt,name=initial_deposit_amount,proto3" json:"initial_deposit_amount,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateAccountReq) Reset() {
	*x = CreateAccountReq{}
	mi := &file_proto_bank_type_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountReq) ProtoMessage() {}

func (x *CreateAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountReq.ProtoReflect.Descriptor instead.
func (*CreateAccountReq) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_account_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountReq) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *CreateAccountReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateAccountReq) GetInitialDepositAmount() float64 {
	if x != nil {
		return x.InitialDepositAmount
	}
	return 0
}

type CreateAccountRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountUuid   string                 `protobuf:"bytes,1,opt,name=account_uuid,proto3" json:"account_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRes) Reset() {
	*x = CreateAccountRes{}
	mi := &file_proto_bank_type_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRes) ProtoMessage() {}

func (x *CreateAccountRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRes.ProtoReflect.Descriptor instead.
func (*CreateAccountRes) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_account_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountRes) GetAccountUuid() string {
	if x != nil {
		return x.AccountUuid
	}
	return ""
}

var File_proto_bank_type_account_proto protoreflect.FileDescriptor

const file_proto_bank_type_account_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/bank/type/account.proto\x12\x04bank\x1a\x1cproto/google/type/date.proto\";\n" +
	"\x11CurrentBalanceReq\x12&\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\x0eaccount_number\"b\n" +
	"\x11CurrentBalanceRes\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x125\n" +
	"\fcurrent_date\x18\x02 \x01(\v2\x11.google.type.DateR\fcurrent_date\"\x8a\x01\n" +
	"\x10CreateAccountReq\x12\"\n" +
	"\faccount_name\x18\x01 \x01(\tR\faccount_name\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\x126\n" +
	"\x16initial_deposit_amount\x18\x03 \x01(\x01R\x16initial_deposit_amount\"6\n" +
	"\x10CreateAccountRes\x12\"\n" +
	"\faccount_uuid\x18\x01 \x01(\tR\faccount_uuidB6Z4github.com/faujiahmat/my-grpc-proto/protogen/go/bankb\x06proto3"

var (
	file_proto_bank_type_account_proto_rawDescOnce sync.Once
	file_proto_bank_type_account_proto_rawDescData []byte
)

func file_proto_bank_type_account_proto_rawDescGZIP() []byte {
	file_proto_bank_type_account_proto_rawDescOnce.Do(func() {
		file_proto_bank_type_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bank_type_account_proto_rawDesc), len(file_proto_bank_type_account_proto_rawDesc)))
	})
	return file_proto_bank_type_account_proto_rawDescData
}

var file_proto_bank_type_account_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_bank_type_account_proto_goTypes = []any{
	(*CurrentBalanceReq)(nil), // 0: bank.CurrentBalanceReq
	(*CurrentBalanceRes)(nil), // 1: bank.CurrentBalanceRes
	(*CreateAccountReq)(nil),  // 2: bank.CreateAccountReq
	(*CreateAccountRes)(nil),  // 3: bank.CreateAccountRes
	(*date.Date)(nil),         // 4: google.type.Date
}
var file_proto_bank_type_account_proto_depIdxs = []int32{
	4, // 0: bank.CurrentBalanceRes.current_date:type_name -> google.type.Date
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_bank_type_account_proto_init() }
func file_proto_bank_type_account_proto_init() {
	if File_proto_bank_type_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_type_account_proto_rawDesc), len(file_proto_bank_type_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bank_type_account_proto_goTypes,
		DependencyIndexes: file_proto_bank_type_account_proto_depIdxs,
		MessageInfos:      file_proto_bank_type_account_proto_msgTypes,
	}.Build()
	File_proto_bank_type_account_proto = out.File
	file_proto_bank_type_account_proto_goTypes = nil
	file_proto_bank_type_account_proto_depIdxs = nil
}
