// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.21.12
// source: proto/bank/type/account.proto

package bank

import (
	date "google.golang.org/genproto/googleapis/type/date"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CurrentBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,proto3" json:"account_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentBalanceReq) Reset() {
	*x = CurrentBalanceReq{}
	mi := &file_proto_bank_type_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentBalanceReq) ProtoMessage() {}

func (x *CurrentBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentBalanceReq.ProtoReflect.Descriptor instead.
func (*CurrentBalanceReq) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_account_proto_rawDescGZIP(), []int{0}
}

func (x *CurrentBalanceReq) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

type CurrentBalanceRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	CurrentDate   *date.Date             `protobuf:"bytes,2,opt,name=current_date,proto3" json:"current_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrentBalanceRes) Reset() {
	*x = CurrentBalanceRes{}
	mi := &file_proto_bank_type_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentBalanceRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentBalanceRes) ProtoMessage() {}

func (x *CurrentBalanceRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentBalanceRes.ProtoReflect.Descriptor instead.
func (*CurrentBalanceRes) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_account_proto_rawDescGZIP(), []int{1}
}

func (x *CurrentBalanceRes) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CurrentBalanceRes) GetCurrentDate() *date.Date {
	if x != nil {
		return x.CurrentDate
	}
	return nil
}

var File_proto_bank_type_account_proto protoreflect.FileDescriptor

const file_proto_bank_type_account_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/bank/type/account.proto\x12\x04bank\x1a\x1cproto/google/type/date.proto\";\n" +
	"\x11CurrentBalanceReq\x12&\n" +
	"\x0eaccount_number\x18\x01 \x01(\tR\x0eaccount_number\"b\n" +
	"\x11CurrentBalanceRes\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x125\n" +
	"\fcurrent_date\x18\x02 \x01(\v2\x11.google.type.DateR\fcurrent_dateB6Z4github.com/faujiahmat/my-grpc-proto/protogen/go/bankb\x06proto3"

var (
	file_proto_bank_type_account_proto_rawDescOnce sync.Once
	file_proto_bank_type_account_proto_rawDescData []byte
)

func file_proto_bank_type_account_proto_rawDescGZIP() []byte {
	file_proto_bank_type_account_proto_rawDescOnce.Do(func() {
		file_proto_bank_type_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bank_type_account_proto_rawDesc), len(file_proto_bank_type_account_proto_rawDesc)))
	})
	return file_proto_bank_type_account_proto_rawDescData
}

var file_proto_bank_type_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bank_type_account_proto_goTypes = []any{
	(*CurrentBalanceReq)(nil), // 0: bank.CurrentBalanceReq
	(*CurrentBalanceRes)(nil), // 1: bank.CurrentBalanceRes
	(*date.Date)(nil),         // 2: google.type.Date
}
var file_proto_bank_type_account_proto_depIdxs = []int32{
	2, // 0: bank.CurrentBalanceRes.current_date:type_name -> google.type.Date
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_bank_type_account_proto_init() }
func file_proto_bank_type_account_proto_init() {
	if File_proto_bank_type_account_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_type_account_proto_rawDesc), len(file_proto_bank_type_account_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bank_type_account_proto_goTypes,
		DependencyIndexes: file_proto_bank_type_account_proto_depIdxs,
		MessageInfos:      file_proto_bank_type_account_proto_msgTypes,
	}.Build()
	File_proto_bank_type_account_proto = out.File
	file_proto_bank_type_account_proto_goTypes = nil
	file_proto_bank_type_account_proto_depIdxs = nil
}
