// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/bank/type/exchange.proto

package bank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExchangeRateReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,proto3" json:"to_currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRateReq) Reset() {
	*x = ExchangeRateReq{}
	mi := &file_proto_bank_type_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateReq) ProtoMessage() {}

func (x *ExchangeRateReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateReq.ProtoReflect.Descriptor instead.
func (*ExchangeRateReq) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *ExchangeRateReq) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ExchangeRateReq) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

type ExchangeRateRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromCurrency  string                 `protobuf:"bytes,1,opt,name=from_currency,proto3" json:"from_currency,omitempty"`
	ToCurrency    string                 `protobuf:"bytes,2,opt,name=to_currency,proto3" json:"to_currency,omitempty"`
	Rate          float64                `protobuf:"fixed64,3,opt,name=rate,proto3" json:"rate,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeRateRes) Reset() {
	*x = ExchangeRateRes{}
	mi := &file_proto_bank_type_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeRateRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeRateRes) ProtoMessage() {}

func (x *ExchangeRateRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bank_type_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeRateRes.ProtoReflect.Descriptor instead.
func (*ExchangeRateRes) Descriptor() ([]byte, []int) {
	return file_proto_bank_type_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *ExchangeRateRes) GetFromCurrency() string {
	if x != nil {
		return x.FromCurrency
	}
	return ""
}

func (x *ExchangeRateRes) GetToCurrency() string {
	if x != nil {
		return x.ToCurrency
	}
	return ""
}

func (x *ExchangeRateRes) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

func (x *ExchangeRateRes) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

var File_proto_bank_type_exchange_proto protoreflect.FileDescriptor

const file_proto_bank_type_exchange_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/bank/type/exchange.proto\x12\x04bank\"Y\n" +
	"\x0fExchangeRateReq\x12$\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\rfrom_currency\x12 \n" +
	"\vto_currency\x18\x02 \x01(\tR\vto_currency\"\x8b\x01\n" +
	"\x0fExchangeRateRes\x12$\n" +
	"\rfrom_currency\x18\x01 \x01(\tR\rfrom_currency\x12 \n" +
	"\vto_currency\x18\x02 \x01(\tR\vto_currency\x12\x12\n" +
	"\x04rate\x18\x03 \x01(\x01R\x04rate\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestampB6Z4github.com/faujiahmat/my-grpc-proto/protogen/go/bankb\x06proto3"

var (
	file_proto_bank_type_exchange_proto_rawDescOnce sync.Once
	file_proto_bank_type_exchange_proto_rawDescData []byte
)

func file_proto_bank_type_exchange_proto_rawDescGZIP() []byte {
	file_proto_bank_type_exchange_proto_rawDescOnce.Do(func() {
		file_proto_bank_type_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bank_type_exchange_proto_rawDesc), len(file_proto_bank_type_exchange_proto_rawDesc)))
	})
	return file_proto_bank_type_exchange_proto_rawDescData
}

var file_proto_bank_type_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bank_type_exchange_proto_goTypes = []any{
	(*ExchangeRateReq)(nil), // 0: bank.ExchangeRateReq
	(*ExchangeRateRes)(nil), // 1: bank.ExchangeRateRes
}
var file_proto_bank_type_exchange_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bank_type_exchange_proto_init() }
func file_proto_bank_type_exchange_proto_init() {
	if File_proto_bank_type_exchange_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bank_type_exchange_proto_rawDesc), len(file_proto_bank_type_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bank_type_exchange_proto_goTypes,
		DependencyIndexes: file_proto_bank_type_exchange_proto_depIdxs,
		MessageInfos:      file_proto_bank_type_exchange_proto_msgTypes,
	}.Build()
	File_proto_bank_type_exchange_proto = out.File
	file_proto_bank_type_exchange_proto_goTypes = nil
	file_proto_bank_type_exchange_proto_depIdxs = nil
}
