// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/resiliency/resiliency.proto

package resiliency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResiliencyReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MinDelaySecond int32                  `protobuf:"varint,1,opt,name=min_delay_second,proto3" json:"min_delay_second,omitempty"`
	MaxDelaySecond int32                  `protobuf:"varint,2,opt,name=max_delay_second,proto3" json:"max_delay_second,omitempty"`
	StatusCodes    []uint32               `protobuf:"varint,3,rep,packed,name=status_codes,json=status_code,proto3" json:"status_codes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResiliencyReq) Reset() {
	*x = ResiliencyReq{}
	mi := &file_proto_resiliency_resiliency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResiliencyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResiliencyReq) ProtoMessage() {}

func (x *ResiliencyReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resiliency_resiliency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResiliencyReq.ProtoReflect.Descriptor instead.
func (*ResiliencyReq) Descriptor() ([]byte, []int) {
	return file_proto_resiliency_resiliency_proto_rawDescGZIP(), []int{0}
}

func (x *ResiliencyReq) GetMinDelaySecond() int32 {
	if x != nil {
		return x.MinDelaySecond
	}
	return 0
}

func (x *ResiliencyReq) GetMaxDelaySecond() int32 {
	if x != nil {
		return x.MaxDelaySecond
	}
	return 0
}

func (x *ResiliencyReq) GetStatusCodes() []uint32 {
	if x != nil {
		return x.StatusCodes
	}
	return nil
}

type ResiliencyRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DummyString   string                 `protobuf:"bytes,1,opt,name=dummy_string,proto3" json:"dummy_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResiliencyRes) Reset() {
	*x = ResiliencyRes{}
	mi := &file_proto_resiliency_resiliency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResiliencyRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResiliencyRes) ProtoMessage() {}

func (x *ResiliencyRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resiliency_resiliency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResiliencyRes.ProtoReflect.Descriptor instead.
func (*ResiliencyRes) Descriptor() ([]byte, []int) {
	return file_proto_resiliency_resiliency_proto_rawDescGZIP(), []int{1}
}

func (x *ResiliencyRes) GetDummyString() string {
	if x != nil {
		return x.DummyString
	}
	return ""
}

var File_proto_resiliency_resiliency_proto protoreflect.FileDescriptor

const file_proto_resiliency_resiliency_proto_rawDesc = "" +
	"\n" +
	"!proto/resiliency/resiliency.proto\x12\n" +
	"resiliency\"\x8a\x01\n" +
	"\rResiliencyReq\x12*\n" +
	"\x10min_delay_second\x18\x01 \x01(\x05R\x10min_delay_second\x12*\n" +
	"\x10max_delay_second\x18\x02 \x01(\x05R\x10max_delay_second\x12!\n" +
	"\fstatus_codes\x18\x03 \x03(\rR\vstatus_code\"3\n" +
	"\rResiliencyRes\x12\"\n" +
	"\fdummy_string\x18\x01 \x01(\tR\fdummy_string2\xe3\x02\n" +
	"\x11ResiliencyService\x12I\n" +
	"\x0fUnaryResiliency\x12\x19.resiliency.ResiliencyReq\x1a\x19.resiliency.ResiliencyRes\"\x00\x12R\n" +
	"\x16ServerStreamResiliency\x12\x19.resiliency.ResiliencyReq\x1a\x19.resiliency.ResiliencyRes\"\x000\x01\x12R\n" +
	"\x16ClientStreamResiliency\x12\x19.resiliency.ResiliencyReq\x1a\x19.resiliency.ResiliencyRes\"\x00(\x01\x12[\n" +
	"\x1dBiDirectionalStreamResiliency\x12\x19.resiliency.ResiliencyReq\x1a\x19.resiliency.ResiliencyRes\"\x00(\x010\x012\x9f\x03\n" +
	"\x1dResiliencyWithMetadataService\x12U\n" +
	"\x1bUnaryResiliencyWithMetadata\x12\x19.resiliency.ResiliencyReq\x1a\x19.resiliency.ResiliencyRes\"\x00\x12^\n" +
	"\"ServerStreamResiliencyWithMetadata\x12\x19.resiliency.ResiliencyReq\x1a\x19.resiliency.ResiliencyRes\"\x000\x01\x12^\n" +
	"\"ClientStreamResiliencyWithMetadata\x12\x19.resiliency.ResiliencyReq\x1a\x19.resiliency.ResiliencyRes\"\x00(\x01\x12g\n" +
	")BiDirectionalStreamResiliencyWithMetadata\x12\x19.resiliency.ResiliencyReq\x1a\x19.resiliency.ResiliencyRes\"\x00(\x010\x01B<Z:github.com/faujiahmat/my-grpc-proto/protogen/go/resiliencyb\x06proto3"

var (
	file_proto_resiliency_resiliency_proto_rawDescOnce sync.Once
	file_proto_resiliency_resiliency_proto_rawDescData []byte
)

func file_proto_resiliency_resiliency_proto_rawDescGZIP() []byte {
	file_proto_resiliency_resiliency_proto_rawDescOnce.Do(func() {
		file_proto_resiliency_resiliency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_resiliency_resiliency_proto_rawDesc), len(file_proto_resiliency_resiliency_proto_rawDesc)))
	})
	return file_proto_resiliency_resiliency_proto_rawDescData
}

var file_proto_resiliency_resiliency_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_resiliency_resiliency_proto_goTypes = []any{
	(*ResiliencyReq)(nil), // 0: resiliency.ResiliencyReq
	(*ResiliencyRes)(nil), // 1: resiliency.ResiliencyRes
}
var file_proto_resiliency_resiliency_proto_depIdxs = []int32{
	0, // 0: resiliency.ResiliencyService.UnaryResiliency:input_type -> resiliency.ResiliencyReq
	0, // 1: resiliency.ResiliencyService.ServerStreamResiliency:input_type -> resiliency.ResiliencyReq
	0, // 2: resiliency.ResiliencyService.ClientStreamResiliency:input_type -> resiliency.ResiliencyReq
	0, // 3: resiliency.ResiliencyService.BiDirectionalStreamResiliency:input_type -> resiliency.ResiliencyReq
	0, // 4: resiliency.ResiliencyWithMetadataService.UnaryResiliencyWithMetadata:input_type -> resiliency.ResiliencyReq
	0, // 5: resiliency.ResiliencyWithMetadataService.ServerStreamResiliencyWithMetadata:input_type -> resiliency.ResiliencyReq
	0, // 6: resiliency.ResiliencyWithMetadataService.ClientStreamResiliencyWithMetadata:input_type -> resiliency.ResiliencyReq
	0, // 7: resiliency.ResiliencyWithMetadataService.BiDirectionalStreamResiliencyWithMetadata:input_type -> resiliency.ResiliencyReq
	1, // 8: resiliency.ResiliencyService.UnaryResiliency:output_type -> resiliency.ResiliencyRes
	1, // 9: resiliency.ResiliencyService.ServerStreamResiliency:output_type -> resiliency.ResiliencyRes
	1, // 10: resiliency.ResiliencyService.ClientStreamResiliency:output_type -> resiliency.ResiliencyRes
	1, // 11: resiliency.ResiliencyService.BiDirectionalStreamResiliency:output_type -> resiliency.ResiliencyRes
	1, // 12: resiliency.ResiliencyWithMetadataService.UnaryResiliencyWithMetadata:output_type -> resiliency.ResiliencyRes
	1, // 13: resiliency.ResiliencyWithMetadataService.ServerStreamResiliencyWithMetadata:output_type -> resiliency.ResiliencyRes
	1, // 14: resiliency.ResiliencyWithMetadataService.ClientStreamResiliencyWithMetadata:output_type -> resiliency.ResiliencyRes
	1, // 15: resiliency.ResiliencyWithMetadataService.BiDirectionalStreamResiliencyWithMetadata:output_type -> resiliency.ResiliencyRes
	8, // [8:16] is the sub-list for method output_type
	0, // [0:8] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_resiliency_resiliency_proto_init() }
func file_proto_resiliency_resiliency_proto_init() {
	if File_proto_resiliency_resiliency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_resiliency_resiliency_proto_rawDesc), len(file_proto_resiliency_resiliency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_resiliency_resiliency_proto_goTypes,
		DependencyIndexes: file_proto_resiliency_resiliency_proto_depIdxs,
		MessageInfos:      file_proto_resiliency_resiliency_proto_msgTypes,
	}.Build()
	File_proto_resiliency_resiliency_proto = out.File
	file_proto_resiliency_resiliency_proto_goTypes = nil
	file_proto_resiliency_resiliency_proto_depIdxs = nil
}
